MvcCoreGiris/Components/SansliKisiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcCoreGiris.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreGiris.Components
{
    public enum TextColor { danger, info, warning, success, primary, secondary, light, dark };

    // https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1
    public class SansliKisiViewComponent : ViewComponent
    {
        private readonly OkulContext okulContext;

        public SansliKisiViewComponent(OkulContext okulContext)
        {
            this.okulContext = okulContext;
        }

        public async Task<IViewComponentResult> InvokeAsync(TextColor renk)
        {
            var adet = await okulContext.Kisiler.CountAsync();
            var index = new Random().Next(adet);
            var kisi = await okulContext.Kisiler.Skip(index).FirstOrDefaultAsync();

            ViewBag.renk = Enum.GetName(renk.GetType(), renk);

            return View(kisi);
        }
    }
}

MvcCoreGiris/Controllers/HavaDurumuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreGiris.Interfaces;

namespace MvcCoreGiris.Controllers
{
    public class HavaDurumuController : Controller
    {
        private readonly IWeatherService weatherService;

        public HavaDurumuController(IWeatherService weatherService)
        {
            this.weatherService = weatherService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SicaklikGetir(string sehirAd)
        {
            try
            {
                return Json(new { sicaklik = weatherService.Temperature(sehirAd) });
            }
            catch (Exception)
            {
                return StatusCode(503);
            }
        }
    }
}

MvcCoreGiris/Controllers/KisilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcCoreGiris.Models;
using MvcCoreGiris.Services;

namespace MvcCoreGiris.Controllers
{
    public class KisilerController : Controller
    {
        private readonly OkulContext db;
        public KisilerController(OkulContext okulContext)
        {
            db = okulContext;
        }

        public IActionResult Index()
        {
            return View(db.Kisiler.ToList());
        }

        public IActionResult Yeni()
        {
            var lns = (LuckyNumberService)HttpContext.RequestServices.GetService(typeof(LuckyNumberService));
            ViewBag.SansliSayi = lns.LuckyNumber;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Yeni(Kisi kisi)
        {
            if (ModelState.IsValid)
            {
                db.Add(kisi); //db.Kisiler.Add(kisi);
                db.SaveChanges();
                TempData["mesaj"] = $"\"{kisi.KisiAd}\" adlı kişi başarıyla eklenmiştir.";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Duzenle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kisi = db.Kisiler.Find(id);

            if (kisi == null)
            {
                return NotFound();
            }

            return View(kisi);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle(Kisi kisi)
        {
            if (ModelState.IsValid)
            {
                // db.Entry(kisi).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.Update(kisi);
                db.SaveChanges();
                TempData["mesaj"] = $"\"{kisi.KisiAd}\" adlı kişinin bilgileri başarıyla güncellenmiştir.";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Sil(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kisi = db.Kisiler.Find(id);

            if (kisi == null)
            {
                return NotFound();
            }

            db.Remove(kisi);
            db.SaveChanges();
            TempData["mesaj"] = $"\"{kisi.KisiAd}\" adlı kişi başarıyla silinmiştir.";
            return RedirectToAction(nameof(Index));
        }
    }
}

MvcCoreGiris/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreGiris</title>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreGiris</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li>
                            <vc:sansli-kisi renk="primary"></vc:sansli-kisi>
                            @await Component.InvokeAsync("SansliKisi", new { renk = TextColor.warning }) 
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HavaDurumu" asp-action="Index">Hava Durumu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kisiler" asp-action="Index">Kişiler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MvcCoreGiris - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/lodash.js/lodash.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>